---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agrued
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tyagipurshottam/argued.git
    targetRevision: HEAD
    path: argued
  destination:
    server: https://kubernetes.default.svc
