---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: purshottam
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/tyagipurshottam/argued.git
    targetRevision: HEAD
    path: my-app2/my-app 
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
      allowEmpty: false 
    # syncOptions: 
    #   - Validate=true
    #   - CreateNamespace=false
    #   - PrunePropagationPolicy=foreground
    #   - PruneLast=true
